// The Ethereum JSON-RPC over a throwaway evm chain: what MetaMask asks, in the order it asks it.
//   node test/evmrpc-test.mjs
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import { loadEngine } from '../lib/engine.mjs'; import { makeSigner } from '../lib/sign.mjs'; import { Siding } from '../lib/chain.mjs';
import { depositScript, GWEI } from '../lib/overlays/evm.mjs'; import { makeEvmRpc } from '../lib/evmrpc.mjs';
const base = JSON.parse(fs.readFileSync(new URL('../chain.json', import.meta.url), 'utf8'));
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'siding-evmrpc-')); let ok = 0, bad = 0;
const t = (name, cond) => { console.log(`  ${cond ? 'PASS' : 'FAIL'}  ${name}`); cond ? ok++ : bad++; };
const engine0 = await loadEngine(base); const signer = makeSigner(engine0); const key = signer.randomKey(), pub = signer.pubkeyOf(key); const me = '5120' + pub;
const chain = { ...base, id: 'sidestr:evmrpctest', name: 'evmrpctest', challenge: me, signer: pub, rules: ['evm'], evm: { chainId: 21474 }, pegs: [{ txid: 'a'.repeat(64), vout: 0, amount: 5e9, script: me }] }; delete chain.genesisHash;
const engine = await loadEngine(chain); const s = await new Siding({ engine, chain, dir, signer, log: () => {} }).open(key); const evm = engine.rules.evm; const { util, tx: T } = evm.lib;
while (s.tip().height < 101) await s.produce(key);
const { SIGHASH_UNIFIED } = await import(`${process.env.SCHEMA ?? os.homedir() + '/bitcoin-desktop/schema'}/codec/interpreter.js`);
const coin = () => s.coins(me).filter((c) => (!c.coinbase || s.tip().height + 1 - c.height >= 100) && !s.mempoolSpent.has(c.outpoint)).sort((a, b) => b.value - a.value)[0];
const mk = (outputs, fee = 5000) => { const c = coin(); const [txid, vout] = c.outpoint.split(':'); const total = outputs.reduce((a, o) => a + o.value, 0); const tx = { version: 2, inputs: [{ prevout: { txid, vout: Number(vout) }, scriptSig: '', sequence: 0xfffffffd }], outputs: [...outputs, { value: c.value - total - fee, scriptPubKey: me }], lockTime: 0, witness: [] }; const prevouts = [{ value: c.value, scriptPubKey: me }]; const ht = 0x01 | SIGHASH_UNIFIED; let m = s.k.interpreter.sighashUnified(tx, 0, prevouts, ht, 2); if (typeof m === 'string') m = engine.hash.hexToBytes(m); tx.witness = [[engine.hash.bytesToHex(signer.schnorrSign(m, key)) + ht.toString(16).padStart(2, '0')]]; return s.k.codec.encodeHex('Transaction', tx); };
const rpc = makeEvmRpc({ s, chain, evm, carrier: (spk) => s.submit(mk([{ value: 0, scriptPubKey: spk }])) });
const call = async (method, params = []) => { const r = await rpc({ jsonrpc: '2.0', id: 1, method, params }); if (r.error) throw Object.assign(new Error(r.error.message), r.error); return r.result; };
const priv = util.hexToBytes('0x' + '42'.repeat(32)); const alice = util.createAddressFromPrivateKey(priv).toString(); const bob = '0x' + '77'.repeat(20);
t('eth_chainId / net_version / eth_blockNumber', (await call('eth_chainId')) === '0x53e2' && (await call('net_version')) === '21474' && (await call('eth_blockNumber')) === '0x65');
t('eth_getBalance of an empty account is 0x0', (await call('eth_getBalance', [alice, 'latest'])) === '0x0');
await s.submit(mk([{ value: 2000000, scriptPubKey: me }, { value: 0, scriptPubKey: depositScript(alice) }])); await s.produce(key);
t('after a deposit of 2,000,000 sats the balance is 2,000,000 gwei', BigInt(await call('eth_getBalance', [alice, 'latest'])) === 2000000n * GWEI);
t('eth_gasPrice is 1 gwei; eth_feeHistory has base fees', (await call('eth_gasPrice')) === '0x3b9aca00' && (await call('eth_feeHistory', ['0x4', 'latest', [50]])).baseFeePerGas.length === 5);
const est = await call('eth_estimateGas', [{ from: alice, to: bob, value: '0x1' }]); t(`eth_estimateGas for a transfer is 21000 (${Number(est)})`, Number(est) === 21000);
const sign = (f, gl = 21000) => '0x' + Buffer.from(T.createLegacyTx({ gasPrice: GWEI, gasLimit: gl, ...f }, { common: evm.common }).sign(priv).serialize()).toString('hex');
const h1 = await call('eth_sendRawTransaction', [sign({ nonce: 0, to: bob, value: 500000n * GWEI })]);
t('eth_sendRawTransaction returns the hash and the carrier sits in the mempool', /^0x[0-9a-f]{64}$/.test(h1) && s.mempool.size === 1);
t('eth_getTransactionCount pending counts the carrier, latest does not', (await call('eth_getTransactionCount', [alice, 'pending'])) === '0x1' && (await call('eth_getTransactionCount', [alice, 'latest'])) === '0x0');
t('the receipt is null until a block', (await call('eth_getTransactionReceipt', [h1])) === null); await s.produce(key);
const rc = await call('eth_getTransactionReceipt', [h1]); t('after the block: receipt status 0x1, gasUsed 0x5208, blockNumber, blockHash', rc?.status === '0x1' && rc.gasUsed === '0x5208' && Number(rc.blockNumber) === s.height() && rc.blockHash === '0x' + s.tip().hash);
const tj = await call('eth_getTransactionByHash', [h1]); t('eth_getTransactionByHash: from, to, value, nonce', tj?.from === alice && tj.to === bob && BigInt(tj.value) === 500000n * GWEI && tj.nonce === '0x0');
t('bob has the 500,000 gwei', BigInt(await call('eth_getBalance', [bob])) === 500000n * GWEI);
const init = '69602a60005260206000f3600052600a6016f3'; const h2 = await call('eth_sendRawTransaction', [sign({ nonce: 1, data: '0x' + init }, 100000)]); await s.produce(key);
const rc2 = await call('eth_getTransactionReceipt', [h2]); const contract = rc2?.contractAddress; t(`a deployment receipt names the contract ${contract?.slice(0, 10)}…`, /^0x[0-9a-f]{40}$/.test(contract ?? ''));
t('eth_getCode returns the runtime', (await call('eth_getCode', [contract])) === '0x602a60005260206000f3');
t('eth_call returns 42 and does not move the state root', (await call('eth_call', [{ to: contract, from: alice }, 'latest'])).endsWith('2a') && (await evm.rootHex()) === evm.blocks.get(s.height()).root);
const blk = await call('eth_getBlockByNumber', ['latest', false]); t('eth_getBlockByNumber latest: number, hash, one transaction, baseFee', Number(blk.number) === s.height() && blk.hash === '0x' + s.tip().hash && blk.transactions.length === 1 && blk.baseFeePerGas === '0x3b9aca00');
t('eth_getBlockByNumber of an unknown height is null', (await call('eth_getBlockByNumber', ['0x7fffffff', false])) === null);
let err = null; try { await call('eth_sendRawTransaction', ['0x1234']); } catch (e) { err = e; } t('a malformed raw transaction is refused with an error', err && /not a transaction/.test(err.message));
let err2 = null; try { await call('eth_call', [{ to: alice, data: '0x' + 'ff'.repeat(4) }]); } catch (e) { err2 = e; } t('a call to an EOA with data succeeds (nothing to run)', !err2);
const batch = await rpc([{ jsonrpc: '2.0', id: 'a', method: 'eth_chainId' }, { jsonrpc: '2.0', id: 'b', method: 'nope' }]); t('a batch answers each, unknown methods with -32601', batch.length === 2 && batch[0].result === '0x53e2' && batch[1].error.code === -32601);
fs.rmSync(dir, { recursive: true, force: true }); console.log(`\n${ok} passed, ${bad} failed`); process.exit(bad ? 1 : 0);
